In [ ]:
import pandas as pd
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

%matplotlib inline

In [3]:
df = pd.read_csv('Smarket.csv', usecols=range(1,9), index_col=0, parse_dates=True)
df.head()

/tmp/ipython-input-2893512417.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('Smarket.csv', usecols=range(1,9), index_col=0, parse_dates=True)


Lag2   Lag3   Lag4   Lag5  Volume  Today Direction
Lag1                                                       
 0.381 -0.192 -2.624 -1.055  5.010  1.1913  0.959        Up
 0.959  0.381 -0.192 -2.624 -1.055  1.2965  1.032        Up
 1.032  0.959  0.381 -0.192 -2.624  1.4112 -0.623      Down
-0.623  1.032  0.959  0.381 -0.192  1.2760  0.614        Up
 0.614 -0.623  1.032  0.959  0.381  1.2057  0.213        Up

In [5]:
import pandas as pd

# Re-load the Smarket.csv to include the 'Year' column for splitting
df_full = pd.read_csv('Smarket.csv')

# Use the 'Year' column to split the data into training and testing sets
X_train = df_full[df_full['Year'] <= 2004][['Lag1','Lag2']]
y_train = df_full[df_full['Year'] <= 2004]['Direction']

X_test = df_full[df_full['Year'] > 2004][['Lag1','Lag2']]
y_test = df_full[df_full['Year'] > 2004]['Direction']

lda = LinearDiscriminantAnalysis()
model = lda.fit(X_train, y_train)

print(model.priors_)

[0.49198397 0.50801603]


In [6]:
print(model.means_)

[[ 0.04279022  0.03389409]
 [-0.03954635 -0.03132544]]


In [7]:
print(model.coef_)

[[-0.05544078 -0.0443452 ]]


In [8]:
pred=model.predict(X_test)
print(np.unique(pred, return_counts=True))

(array(['Down', 'Up'], dtype='<U4'), array([ 70, 182]))


In [9]:
print(confusion_matrix(pred, y_test))
print(classification_report(y_test, pred, digits=3))

[[ 35  35]
 [ 76 106]]
              precision    recall  f1-score   support

        Down      0.500     0.315     0.387       111
          Up      0.582     0.752     0.656       141

    accuracy                          0.560       252
   macro avg      0.541     0.534     0.522       252
weighted avg      0.546     0.560     0.538       252



In [10]:
qda = QuadraticDiscriminantAnalysis()
model2 = qda.fit(X_train, y_train)
print(model2.priors_)
print(model2.means_)

[0.49198397 0.50801603]
[[ 0.04279022  0.03389409]
 [-0.03954635 -0.03132544]]


In [11]:
pred2=model2.predict(X_test)
print(np.unique(pred2, return_counts=True))
print(confusion_matrix(pred2, y_test))
print(classification_report(y_test, pred2, digits=3))


(array(['Down', 'Up'], dtype=object), array([ 50, 202]))
[[ 30  20]
 [ 81 121]]
              precision    recall  f1-score   support

        Down      0.600     0.270     0.373       111
          Up      0.599     0.858     0.706       141

    accuracy                          0.599       252
   macro avg      0.600     0.564     0.539       252
weighted avg      0.599     0.599     0.559       252



In [14]:


df2 = pd.read_csv('Carseats.csv')
df2.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No